### ISSUE TITLE
Could not find the groundtruth file(txt file) in the code

### ISSUE THREAD

**Issue by NjuHaoZhang** [drsagitn/anomaly-detection-and-localization#1]
https://github.com/drsagitn/anomaly-detection-and-localization/blob/6c7b745d613cf0c4529629f9e9862d5ef641a08a/classifier.py#L164
https://github.com/drsagitn/anomaly-detection-and-localization/blob/6c7b745d613cf0c4529629f9e9862d5ef641a08a/classifier.py#L166
https://github.com/drsagitn/anomaly-detection-and-localization/blob/6c7b745d613cf0c4529629f9e9862d5ef641a08a/classifier.py#L187

Hi drsagitn,  I'm hao.  Thank you very much for your great code, which has helped me a lot.

I have the following questions when reading your code:

(1) the `groundtruths/*.txt` ,  `gt_files/*.txt`  and `gt` mentioned in your code <b>cannot</b> be found in the `avenue` and `UCSD` dataset obtained from the official download page.

(2) the labels provided by `avenue/UCSD pedx` are all `matlab`  files, but the label files used by your code are all `txt` files.  <b>Have you ever processed them?</b>

So, how do I access these `txt` files to continue the experiment?
Looking forward to your reply. Thank you again!

**Comment by drsagitn** [comment]
I pushed the groundtruth txt file for ped1 and ped2.

**Comment by LeilaMaria** [comment]
How can we obtain it for avenue?

**Comment by baxiazwf** [comment]
如何获取上面提到的文件，请帮助我一下，非常期待您的回复
